#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -rf 0.org 0
./scripts/meshgen.m
runApplication blockMesh
runApplication createPatch -overwrite
simpleFoam | tee log.simpleFoam
