stages:
  naca0012-re2e5:
    foreach: ${aoa-values}
    do:
      cmd: calkit xenv python run.py 0012 ${item}
      deps:
        - system/controlDict
        - system/fvSchemes
        - system/fvSolution
        - system/createPatchDict
        - system/surfaces
        - constant/transportProperties
        - constant/turbulenceProperties
        - run.py
        - scripts/blockmeshdict.py
        - 0.org
        - Dockerfile
      outs:
        - cases/naca0012-re2e5-aoa-${item}
  aggregate-results:
    cmd: calkit xenv -n py python scripts/aggregate.py
    deps:
      - scripts/aggregate.py
      - cases
    outs:
      - processed/all-simulated.csv:
          cache: false
    meta:
      calkit:
        type: dataset
        title: All simulation results
  plot-clcd:
    cmd: calkit xenv -n py python scripts/plot-clcd.py
    deps:
      - scripts/plot-clcd.py
      - processed/all-simulated.csv
    outs:
      - figures/naca0012-clcd.json:
          cache: false
    meta:
      calkit:
        type: figure
        title: NACA 0012 lift-to-drag ratio
        description: >
          Plotted against the Ladson 180 grit experimental data.
  plot-flow:
    foreach: ${aoa-values}
    do:
      cmd: calkit xenv -n py python scripts/plot-flow.py ${item}
      deps:
        - scripts/plot-flow.py
        - cases/naca0012-re2e5-aoa-${item}/postProcessing/surfaces
      outs:
        - figures/naca0012-re2e5-aoa-${item}-umag.png
        - figures/naca0012-re2e5-aoa-${item}-umag.html
  build-app:
    cmd: bash scripts/build-app.sh
    deps:
      - scripts/build-app.sh
      - figures
      - processed
      - requirements.txt
      - notebook.py
      - layouts
    outs:
      - app:
          cache: false
          persist: true
